# Build stage
FROM node:20 AS production
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

#dev stage
FROM node:20-slim as development
WORKDIR /app

# Install dependencies first (including platform-specific ones)
COPY package*.json ./
RUN npm install
RUN npm install @rollup/rollup-linux-arm64-gnu

# Copy the rest of the application
COPY . .

EXPOSE 3000

# Use Vite's development server
CMD ["npm", "run", "dev", "--", "--host"]

# Production stage
FROM nginx:alpine
COPY --from=production /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

