services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
