services:
  # Backend API service
  - type: web
    name: backend-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FASTAPI_ENV
        value: production
    autoDeploy: true

  # Frontend static site
  - type: web
    name: frontend-app
    env: node
    rootDir: frontend
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    autoDeploy: true
